oppijanumerorekisteri-api/src/main/java/fi/vm/sade/oppijanumerorekisteri/dto/HenkiloPerustietoDto.java, oppijanumerorekisteri-api/src/main/java/fi/vm/sade/oppijanumerorekisteri/utils/DtoUtils.java, oppijanumerorekisteri-api/src/main/java/fi/vm/sade/oppijanumerorekisteri/validation/FindOrNewHenkilo.java, oppijanumerorekisteri-api/src/test/java/fi/vm/sade/oppijanumerorekisteri/api/HenkiloJsonTest.java, oppijanumerorekisteri-api/src/test/resources/henkilo/testHenkiloPerustietoDto.json, oppijanumerorekisteri-domain/src/main/java/fi/vm/sade/oppijanumerorekisteri/repositories/HenkiloRepository.java, oppijanumerorekisteri-domain/src/main/java/fi/vm/sade/oppijanumerorekisteri/repositories/impl/HenkiloRepositoryImpl.java, oppijanumerorekisteri-domain/src/test/java/fi/vm/sade/oppijanumerorekisteri/mappers/HenkiloMapperTest.java, oppijanumerorekisteri-domain/src/test/java/fi/vm/sade/oppijanumerorekisteri/repositories/HenkiloRepositoryTests.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/aspects/AuditlogAspect.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/aspects/GlobalExceptionHandler.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/controllers/HenkiloController.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/controllers/Service2ServiceController.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/exceptions/DuplicateHetuException.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/HenkiloService.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/HenkiloServiceImpl.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/controllers/HenkiloControllerTest.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/controllers/Service2ServiceControllerTest.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/services/HenkiloServiceTest.java
- /s2s/oid/oidExists => HEAD /henkilo/oid
- /s2s/findOrCreate
=> Kjhh 879: koski api 

oppijanumerorekisteri-api/src/main/java/fi/vm/sade/oppijanumerorekisteri/dto/HenkiloCreateDto.java, oppijanumerorekisteri-api/src/main/java/fi/vm/sade/oppijanumerorekisteri/dto/HenkiloUpdateDto.java, oppijanumerorekisteri-api/src/main/java/fi/vm/sade/oppijanumerorekisteri/utils/DtoUtils.java, oppijanumerorekisteri-api/src/main/java/fi/vm/sade/oppijanumerorekisteri/validation/ExistingHenkilo.java, oppijanumerorekisteri-api/src/main/java/fi/vm/sade/oppijanumerorekisteri/validation/FindOrNewHenkilo.java, oppijanumerorekisteri-api/src/main/java/fi/vm/sade/oppijanumerorekisteri/validation/NewHenkilo.java, oppijanumerorekisteri-domain/src/main/java/fi/vm/sade/oppijanumerorekisteri/repositories/HenkiloRepository.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/controllers/HenkiloController.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/HenkiloService.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/HenkiloServiceImpl.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/controllers/HenkiloControllerTest.java
- Change PUT /henkilo/updateHenkilo to PUT /henkilo
- Create HenkiloCreateDto for POST /henkilo
=> Kjhh 893: small refactor to create and update

oppijanumerorekisteri-api/src/main/java/fi/vm/sade/oppijanumerorekisteri/dto/HenkiloUpdateDto.java, oppijanumerorekisteri-api/src/main/java/fi/vm/sade/oppijanumerorekisteri/utils/DtoUtils.java, oppijanumerorekisteri-domain/src/main/java/fi/vm/sade/oppijanumerorekisteri/dto/Slice.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/controllers/HenkiloController.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/HenkiloService.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/HenkiloServiceImpl.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/PermissionCheckerImpl.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/validators/HenkiloUpdatePostValidator.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/controllers/HenkiloControllerTest.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/services/HenkiloServiceTest.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/services/PermissionCheckerTest.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/services/YksilointiServiceTest.java
- Ei voi päivittää äidinkieli ja kansalaisuus jos VTJ yksiloity
- Poistin henkilön päivitettävistä tiedoista henkiloTyyppi ja eiSuomalaistaHetua
- Sallin omien tietojen päivityksen henkilön tietoja päivitettäessä validoinnissa ja käyttöoikeuksien tarkistuksessa
=> Kjhh 1013: omien tietojen muokkaus ONR

oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/aspects/AuditlogAspect.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/aspects/AuditlogAspectHelper.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/HenkiloService.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/HenkiloServiceImpl.java
Audit logging contains:
henkiloOid of the person doing the action
henkiloOid of the person receiving the action
type of the action
Change details or deltas are not logged.
=> KJHH-1024: Add audit logging to all service methods that make changes to db

oppijanumerorekisteri-api/src/main/java/fi/vm/sade/oppijanumerorekisteri/dto/HenkiloCreateDto.java, oppijanumerorekisteri-api/src/main/java/fi/vm/sade/oppijanumerorekisteri/dto/HenkiloDuplikaattiCriteria.java, oppijanumerorekisteri-api/src/main/java/fi/vm/sade/oppijanumerorekisteri/utils/DtoUtils.java, oppijanumerorekisteri-domain/src/main/java/fi/vm/sade/oppijanumerorekisteri/repositories/HenkiloJpaRepository.java, oppijanumerorekisteri-domain/src/main/java/fi/vm/sade/oppijanumerorekisteri/repositories/impl/HenkiloRepositoryImpl.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/controllers/HenkiloController.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/controllers/OppijaController.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/HenkiloService.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/OppijaService.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/HenkiloServiceImpl.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/OppijaServiceImpl.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/services/HenkiloServiceTest.java
Käyttöliittymä oppijan luontiin tarvitsee seuraavat lisäykset:
1) Passinumeroiden tallennus luonnin yhteydessä
2) Rajapinta duplikaattien hakuun nimellä
3) Oppijan liittäminen käyttäjän organisaatioihin luonnin yhteydessä
=> KJHH-1081: Oppijan luonti

oppijanumerorekisteri-domain/src/main/java/fi/vm/sade/oppijanumerorekisteri/models/Henkilo.java, oppijanumerorekisteri-domain/src/main/java/fi/vm/sade/oppijanumerorekisteri/repositories/HenkiloJpaRepository.java, oppijanumerorekisteri-domain/src/main/java/fi/vm/sade/oppijanumerorekisteri/repositories/impl/HenkiloRepositoryImpl.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/controllers/HenkiloController.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/HenkiloService.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/PermissionChecker.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/HenkiloServiceImpl.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/PermissionCheckerImpl.java
Needed an api that returns persons for an oid list and if there is a master to that person, then the master person related to the slave oid which was used in the query.
=> Hle 315 mass api for master persons

oppijanumerorekisteri-domain/src/main/java/fi/vm/sade/oppijanumerorekisteri/repositories/HenkiloJpaRepository.java, oppijanumerorekisteri-domain/src/main/java/fi/vm/sade/oppijanumerorekisteri/repositories/HenkiloRepository.java, oppijanumerorekisteri-domain/src/main/java/fi/vm/sade/oppijanumerorekisteri/repositories/impl/AbstractRepository.java, oppijanumerorekisteri-domain/src/main/java/fi/vm/sade/oppijanumerorekisteri/repositories/impl/HenkiloRepositoryImpl.java, oppijanumerorekisteri-domain/src/test/java/fi/vm/sade/oppijanumerorekisteri/repositories/HenkiloRepositoryTests.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/clients/impl/MuutostietoClientImpl.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/configurations/properties/OppijanumerorekisteriProperties.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/configurations/scheduling/ScheduledTasks.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/dto/MuutostietoHetus.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/HenkiloService.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/DuplicateServiceImpl.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/HenkiloServiceImpl.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/IdentificationServiceImpl.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/OppijaServiceImpl.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/OppijaTuontiServiceImpl.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/validators/HenkiloUpdatePostValidator.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/services/HenkiloServiceTest.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/services/OppijaServiceTest.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/services/impl/DuplicateServiceImplTest.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/services/impl/HenkiloServiceImplTest.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/services/impl/OppijaServiceImplTest.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/validators/HenkiloUpdatePostValidatorTest.java
- Oppijanumerorekisteri päivittämään uudet hetulliset henkilotietomuutospalveluun pienemmissä erissä
- Henkilötietomuutospalveluun päivitetään vain vtj-yksilöidyt
- Refaktorointia henkilörepositoryyn
- Property-tiedostojen korjaamista scheduled taskeille
=> KJHH-1317: henkilotietomuutos hetu updates

oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/HenkiloModificationServiceImpl.java
Sallii vain luku -yhteystietojen päivittämisen muutostietopalvelusta
=> KJHH-1264: Yhteystietojen päivittäminen muutospalvelusta

oppijanumerorekisteri-api/src/main/java/fi/vm/sade/oppijanumerorekisteri/dto/HenkiloReadDto.java
Korjaa henkilötietomuutospalvelun yhteystietopäivityksen
=> KJHH-1350: Lisää yhteystiedot hetulla hakuun

oppijanumerorekisteri-api/src/main/java/fi/vm/sade/oppijanumerorekisteri/dto/HenkiloPerustietoDto.java, oppijanumerorekisteri-api/src/main/java/fi/vm/sade/oppijanumerorekisteri/utils/DtoUtils.java, oppijanumerorekisteri-domain/src/main/java/fi/vm/sade/oppijanumerorekisteri/repositories/impl/HenkiloRepositoryImpl.java, oppijanumerorekisteri-service/src/test/resources/henkilo/testHenkiloPerustietoDto.json
Koski-palvelu tarvitsee turvakielto-tiedon. Parempi varmaan lisätä tämä _henkiloPerustietosByHenkiloOidList_-apiin kuin ruveta käyttämään raskaampaa _henkilotByHenkiloOidList_-kyselyä.
=> Lisää turvakielto henkilön perustietoihin

oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/controllers/Service2ServiceController.java
- Lisää rooli APP_OPPIJANUMEROREKISTERI_MUUTOSTIETOPALVELU oppijanumerorekisterin s2s rajapintaan
=> KJHH-1356_onr_muutostietopalvelu

oppijanumerorekisteri-domain/src/main/java/fi/vm/sade/oppijanumerorekisteri/mappers/EntityUtils.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/DuplicateService.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/DuplicateServiceImpl.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/HenkiloModificationServiceImpl.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/IdentificationServiceImpl.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/TestApplication.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/services/HenkiloModificationServiceIntegrationTest.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/services/impl/DuplicateServiceImplTest.java, oppijanumerorekisteri-service/src/test/resources/sql/henkilo-modification-test.sql
- Sallii hetun päivittämisen henkilotietomuutos-rajapinnasta
- Jos toisella henkilöllä löytyy jo hetu linkittää henkilöt
=> KJHH-1288 hetun päivitys

oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/YksilointiServiceImpl.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/services/YksilointiServiceTest.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/services/YksilointiTests.java
- Yksilöinnin yhteydessä tehtävässä hetun päivityksessä linkitetään mahdollisesti uudella hetulla löytyvä henkilö
=> KJHH-1374_yksilointi_hetupaivitys

oppijanumerorekisteri-domain/src/main/java/fi/vm/sade/oppijanumerorekisteri/repositories/TuontiRepositoryCustom.java, oppijanumerorekisteri-domain/src/main/java/fi/vm/sade/oppijanumerorekisteri/repositories/impl/TuontiRepositoryImpl.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/OppijaServiceImpl.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/PermissionCheckerImpl.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/services/OppijaServiceTest.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/services/PermissionCheckerTest.java
- Hakee muistiin vain tarvittavat asiat
- Hakee muistiin myös yhteystietoryhmät ja yhteystiedot
- Lisää isSuperUser() juuriorganisaatiovaateen
=> KJHH-1422_tuonti_lazy_loading_optimointi

oppijanumerorekisteri-api/src/main/java/fi/vm/sade/oppijanumerorekisteri/dto/HenkiloOmattiedotDto.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/controllers/HenkiloController.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/mappers/HenkiloOmattiedotDtoConverter.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/HenkiloService.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/HenkiloServiceImpl.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/UserDetailsHelperImpl.java
- Lisää /henkilo/current/omattiedot josta UI voi hakea käyttäjän omattiedot oppijanumerorekisteristä
- Lisää /henkilo/oid/omattiedot CAS:ia varten
=> KJHH-1426_cas_myroles

oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/clients/impl/KayttooikeusClientImpl.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/YksilointiServiceImpl.java, oppijanumerorekisteri-service/src/main/resources/db/migration/V20180912162716643__yksilointivirhe_korjaus.sql, oppijanumerorekisteri-service/src/main/resources/db/migration/V20180913095545479__yksilointivirhe_404.sql
=> Korjaa 404-virheen käsittelyn yksilöinnissä

oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/YksilointiServiceImpl.java, oppijanumerorekisteri-service/src/main/resources/db/migration/V20180912162716643__yksilointivirhe_korjaus.sql
=> Korjaa yksilöintivirheen poistamisen

oppijanumerorekisteri-domain/src/main/java/fi/vm/sade/oppijanumerorekisteri/models/Tuonti.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/clients/KayttooikeusClient.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/clients/OrganisaatioClient.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/clients/impl/KayttooikeusClientImpl.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/clients/impl/OrganisaatioClientImpl.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/dto/OrganisaatioTilat.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/OppijaTuontiService.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/OrganisaatioService.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/PermissionChecker.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/OppijaServiceImpl.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/OppijaTuontiServiceImpl.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/OrganisaatioServiceImpl.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/PermissionCheckerImpl.java, oppijanumerorekisteri-service/src/main/resources/db/migration/V20180914155659023__tuonti_organisaatio.sql, oppijanumerorekisteri-service/src/main/resources/oppijanumerorekisteri-service-oph.properties, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/clients/impl/OrganisaatioClientImplTest.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/services/OppijaServiceTest.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/services/PermissionCheckerTest.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/services/impl/OppijaServiceImplTest.java
KJHH-1452
Poistaa samalla riippuvuuden käyttöoikeuspalveluun oppijoiden tuonnista.
=> Lisää oppijan tuontiin aliorganisaatio-oikeudet

oppijanumerorekisteri-domain/src/main/java/fi/vm/sade/oppijanumerorekisteri/models/TuontiRivi.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/OppijaTuontiServiceImpl.java, oppijanumerorekisteri-service/src/main/resources/db/migration/V20181005130641693__oppijoidentuontiindex.sql, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/services/OppijaServiceTest.java
Käsittely ei toiminut jos sama hetu annettiin useampaan kertaan.
=> KJHH-1462: Korjaa oppijoiden tuonnin käsittelyn

oppijanumerorekisteri-domain/src/main/java/fi/vm/sade/oppijanumerorekisteri/models/TuontiRivi.java, oppijanumerorekisteri-domain/src/main/java/fi/vm/sade/oppijanumerorekisteri/repositories/criteria/OppijaTuontiCriteria.java, oppijanumerorekisteri-domain/src/test/java/fi/vm/sade/oppijanumerorekisteri/repositories/HenkiloRepositoryTests.java, oppijanumerorekisteri-domain/src/test/java/fi/vm/sade/oppijanumerorekisteri/repositories/populator/HenkiloPopulator.java, oppijanumerorekisteri-domain/src/test/java/fi/vm/sade/oppijanumerorekisteri/repositories/populator/TuontiPopulator.java
Passivoidut ja duplikaatit merkittiin virheellisesti virheiksi.
KJHH-1476
=> Korjaa oppijoiden tuonnin "vain virheet"-napin

oppijanumerorekisteri-api/src/main/java/fi/vm/sade/oppijanumerorekisteri/enums/YksilointivirheTila.java, oppijanumerorekisteri-domain/src/main/java/fi/vm/sade/oppijanumerorekisteri/mappers/YksilointivirheDtoMapper.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/YksilointiServiceImpl.java
=> Lisää passivoidun hetun käsittelyn yksilöintiin

oppijanumerorekisteri-api/src/main/java/fi/vm/sade/oppijanumerorekisteri/dto/KoodiUpdateDto.java, oppijanumerorekisteri-api/src/main/java/fi/vm/sade/oppijanumerorekisteri/dto/OppijaReadDto.java, oppijanumerorekisteri-api/src/main/java/fi/vm/sade/oppijanumerorekisteri/dto/OppijaTuontiRiviCreateDto.java, oppijanumerorekisteri-domain/src/main/java/fi/vm/sade/oppijanumerorekisteri/models/Henkilo.java, oppijanumerorekisteri-domain/src/main/java/fi/vm/sade/oppijanumerorekisteri/models/Kielisyys.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/mappers/OppijaMappers.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/OppijaTuontiServiceImpl.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/validators/OppijaTuontiCreatePostValidator.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/DatabaseService.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/mappers/OppijaMappersTest.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/services/OppijaServiceTest.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/services/impl/OppijaServiceImplTest.java
Uudet kentät: sukupuoli, äidinkieli, kansalaisuus.
KJHH-1480
=> Lisää oppijoiden tuontiin uusia kenttiä

oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/HenkiloModificationServiceImpl.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/services/impl/HenkiloModificationServiceImplTest.java
=> Korjaa syntymäajan ja sukupuolen hetumuutoksessa

oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/controllers/OppijaController.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/OppijaServiceImpl.java
Korjaa oppijan luonnin rekisterinpitäjänä.
KJHH-1488
=> Poistaa oppijan luonnista organisaatiolinkityksen

oppijanumerorekisteri-domain/src/main/java/fi/vm/sade/oppijanumerorekisteri/repositories/criteria/OppijaTuontiCriteria.java, oppijanumerorekisteri-service/src/main/resources/db/migration/V20181107143652304__oppijahaku_index.sql, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/services/OppijaServiceTest.java
- Oppijoiden hakeminen nimen perusteella
=> KJHH-1479: oppija nimihaku

oppijanumerorekisteri-domain/src/main/java/fi/vm/sade/oppijanumerorekisteri/models/Henkilo.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/HenkiloModificationServiceImpl.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/services/HenkiloModificationServiceIntegrationTest.java, oppijanumerorekisteri-service/src/test/resources/sql/henkilo-modification-test.sql
Linkitys ei toiminut jos tulevalle slavelle oli ehditty lisäämään
vanha hetu "kaikkiHetut"-listaan.
KJHH-1514
=> Korjaa henkilötietomuutospalvelun tekemän linkityksen

oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/YksilointiServiceImpl.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/services/YksilointiServiceTest.java
=> Korjaa yksilöinnin uudelleenyrityksen

oppijanumerorekisteri-service/pom.xml, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/clients/impl/HakuappClientImpl.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/clients/impl/HttpClientUtil.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/clients/impl/KayttooikeusClientImpl.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/clients/impl/VtjClientImpl.java, pom.xml
=> Poistaa generic cachingrestclientin käytön

oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/clients/KayttooikeusClient.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/clients/impl/KayttooikeusClientImpl.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/configurations/security/SecurityDevConfiguration.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/controllers/CasController.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/controllers/HenkiloController.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/controllers/OppijaController.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/controllers/Service2ServiceController.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/HenkiloService.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/PermissionChecker.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/HenkiloServiceImpl.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/PermissionCheckerImpl.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/services/HenkiloModificationServiceIntegrationTest.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/services/PermissionCheckerTest.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/services/YksilointiITest.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/services/impl/HenkiloServiceImplTest.java
- Poistaa vanhat henkilön- ja anomustenhallinan käyttöoikeudet oppijanumerorekisteristä
=> KJHH-1277 vanhat oikeudet

oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/controllers/HenkiloController.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/PermissionChecker.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/PermissionCheckerImpl.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/controllers/HenkiloControllerTest.java
- Vaatii kunnolliset oikeudet /henkilo/henkiloPerustietosByHenkiloHetuList api:n käyttämiseksi.
- Kosken tekemä rajapinta joka ei ole vielä tuotantokäytössä ja kutsutaan palvelukäyttäjänä rekisterinpitäjän oikeuksilla
=> KJHH-1538: henkiloPerustietosByHenkiloHetuList rajapinnan oikeudet

oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/PermissionCheckerImpl.java, oppijanumerorekisteri-service/src/main/resources/db/migration/V20190108110102348__clear_sessions.sql, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/controllers/HenkiloControllerTest.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/controllers/OppijaControllerTest.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/controllers/Service2ServiceControllerTest.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/services/HenkiloModificationServiceIntegrationTest.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/services/YksilointiITest.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/services/YksilointiServiceTest.java, oppijanumerorekisteri-service/src/test/resources/application.yml, pom.xml
- SpringMvcTestit sisältävät nyt spring security filtterin jolloin testeihin tarvitaan lisää luokkia
- Tyhjentää vanhat sessiot
=> KJHH-1543: Update to spring-boot 2.1.1. 

oppijanumerorekisteri-service/pom.xml, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/clients/KayttooikeusClient.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/clients/impl/KayttooikeusClientImpl.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/HenkiloModificationServiceImpl.java, oppijanumerorekisteri-service/src/main/resources/oppijanumerorekisteri-service-oph.properties, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/services/impl/HenkiloModificationServiceImplTest.java, pom.xml
- Poistaa kutsut käyttöoikeuspalvelun dlap rajapintaan asiointikieltä muutettaessa
- Poistaa vanhat ldap riippuvuudet
=> KJHH-1535: ldap poisto

oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/controllers/HenkiloController.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/controllers/OppijaController.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/controllers/Service2ServiceController.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/PermissionChecker.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/HenkiloServiceImpl.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/OppijaServiceImpl.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/PermissionCheckerImpl.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/services/HenkiloServiceTest.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/services/OppijaServiceTest.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/services/PermissionCheckerTest.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/services/impl/OppijaServiceImplTest.java
- Lisää rekisteinpitäjä read oikeuden lukurajapintoihin
- Erittelee hieman luku ja muokkaus oikeuksia
=> KJHH-1539 rekisterinpitaja read

oppijanumerorekisteri-api/src/main/java/fi/vm/sade/oppijanumerorekisteri/dto/HenkiloCreateDto.java, oppijanumerorekisteri-api/src/main/java/fi/vm/sade/oppijanumerorekisteri/dto/HenkiloUpdateDto.java, oppijanumerorekisteri-api/src/main/java/fi/vm/sade/oppijanumerorekisteri/dto/HuoltajaCreateDto.java, oppijanumerorekisteri-api/src/main/java/fi/vm/sade/oppijanumerorekisteri/dto/OppijaCreateDto.java, oppijanumerorekisteri-api/src/main/java/fi/vm/sade/oppijanumerorekisteri/dto/YhteystiedotRyhmaDto.java, oppijanumerorekisteri-api/src/main/java/fi/vm/sade/oppijanumerorekisteri/dto/YhteystietoDto.java, oppijanumerorekisteri-service/src/main/resources/db/migration/V20190123091416023__yhteystietotyyppi_not_null.sql, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/controllers/HenkiloControllerTest.java
- validoi yhteystietotyypit rajapinnassa ei nulliksi
- asettaa kantaan ei null -rajoitteen yhteystietotyyppiin
=> KJHH-1547 yhteystietotyyppi validointi

oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/CookieConfiguration.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/configurations/CookieConfiguration.java, src/main/resources/oph-configuration/oppijanumerorekisteri.yml.template
- Mahdollistaa keksin SameSite attribuutin jättämisen pois
- Tarkoitettu konfiguroitavaksi testiympäristöön
- Oletuksena pois käytöstä
=> KJHH-1546 same site cookie

pom.xml
- Nostaa käyttöoikeus-apin versiota VARDA permission check headerin sisältävään versioon
=> KJHH-1551: Support varda external permission service.

oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/dto/OrganisaatioTilat.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/OppijaServiceImpl.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/OppijaTuontiServiceImpl.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/PermissionCheckerImpl.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/services/OppijaServiceTest.java
- Näyttää lakkautettuihin organisaatioihin liitetyt oppijat oppijan tuonnissa.
=> KJHH-1557: Lakkautetut oppijantuontiorganisaatiot

oppijanumerorekisteri-api/src/main/java/fi/vm/sade/oppijanumerorekisteri/dto/HenkiloCreateDto.java, oppijanumerorekisteri-api/src/main/java/fi/vm/sade/oppijanumerorekisteri/dto/HenkiloDto.java, oppijanumerorekisteri-api/src/main/java/fi/vm/sade/oppijanumerorekisteri/dto/HenkiloReadDto.java, oppijanumerorekisteri-api/src/main/java/fi/vm/sade/oppijanumerorekisteri/dto/HenkiloUpdateDto.java, oppijanumerorekisteri-api/src/main/java/fi/vm/sade/oppijanumerorekisteri/utils/DtoUtils.java, oppijanumerorekisteri-domain/src/main/java/fi/vm/sade/oppijanumerorekisteri/mappers/EntityUtils.java, oppijanumerorekisteri-domain/src/main/java/fi/vm/sade/oppijanumerorekisteri/models/Henkilo.java, oppijanumerorekisteri-domain/src/test/java/fi/vm/sade/oppijanumerorekisteri/mappers/HenkiloMapperTest.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/HenkiloModificationServiceImpl.java, oppijanumerorekisteri-service/src/main/resources/db/migration/V20190305121306632__kielisyys_poisto.sql.todo, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/services/impl/HenkiloModificationServiceImplTest.java, oppijanumerorekisteri-service/src/test/resources/henkilo/testHenkiloDto.json
=> Poistaa turhan henkilö<->kielisyys linkityksen

oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/DuplicateServiceImpl.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/services/HenkiloModificationServiceTest.java
Lisää kansalaisuuden ja äidinkielen kopioinnin henkilöiden linkitykseen.
KJHH-1622
=> Henkilöiden linkityksen parannuksia

oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/YksilointiServiceImpl.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/services/YksilointiServiceTest.java
=> Korjaa yksilöinnin kutsumanimen asettamisen

oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/configurations/scheduling/HenkilotietomuutosHetuSyncTask.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/MuutostietoService.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/MuutostietoServiceImpl.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/configurations/scheduling/HenkilotietomuutosHetuSyncTaskTest.java
=> Korjaa vtjregister-bitin asettamisen

oppijanumerorekisteri-domain/src/main/java/fi/vm/sade/oppijanumerorekisteri/repositories/HenkiloJpaRepository.java, oppijanumerorekisteri-domain/src/main/java/fi/vm/sade/oppijanumerorekisteri/repositories/impl/HenkiloRepositoryImpl.java, oppijanumerorekisteri-domain/src/test/java/fi/vm/sade/oppijanumerorekisteri/repositories/HenkiloRepositoryTests.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/controllers/HenkiloController.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/HenkiloService.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/HenkiloServiceImpl.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/controllers/HenkiloControllerTest.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/services/HenkiloServiceTest.java
=> Korjaa käyttöoikeustarkistuksia

oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/YksilointiServiceImpl.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/services/YksilointiServiceTest.java, oppijanumerorekisteri-service/src/test/resources/vtj-testdata/vtj-response-vaarat-kentat.json
=> Korjaa nimivertailun jos nimet on väärissä kentissä

oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/HenkiloServiceImpl.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/services/HenkiloServiceTest.java
=> Huoltajahaku palauttaa 404:n sijaan tyhjän listan.

oppijanumerorekisteri-service/src/main/resources/db/migration/V20190924095801294_tyosahkoposti_muokattavaksi.sql
=> KJHH-1704 työsähköposti muokattavaksi

.travis.yml, oppijanumerorekisteri-service/pom.xml
Testien päätteeksi ajetaan Flyway-migraatiot Maven-plugarilla CI-palvelimen possukantaa vasten.
=> Ajetaan kantamigraatiot CI-buildissa

oppijanumerorekisteri-domain/src/main/java/fi/vm/sade/oppijanumerorekisteri/models/Henkilo.java, oppijanumerorekisteri-service/src/main/resources/db/migration/V20200123104943740__turvakielto_eisuomalaistahetua_not_null.sql, oppijanumerorekisteri-service/src/test/resources/sql/henkilo-modification-test.sql, oppijanumerorekisteri-service/src/test/resources/sql/yksilointi-test.sql, oppijanumerorekisteri-service/src/test/resources/sql/yksilointi-test2.sql
Lisätty `NOT NULL DEFAULT false` kantaan. Entitylle
`nullable=false`.
=> Sarakkeet "eisuomalaistahetua" ja "turvakielto" pakollisiksi.

oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/HenkiloModificationServiceImpl.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/services/impl/HenkiloModificationServiceImplTest.java
* hetu is defined to be unique in db schema -> cannot default
to emtpy string
=> KJHH-2009: Try to ensure that empty hetus are saved as null

oppijanumerorekisteri-api/src/main/java/fi/vm/sade/oppijanumerorekisteri/dto/HenkiloMunicipalDobDto.java, oppijanumerorekisteri-domain/src/main/java/fi/vm/sade/oppijanumerorekisteri/repositories/HenkiloJpaRepository.java, oppijanumerorekisteri-domain/src/main/java/fi/vm/sade/oppijanumerorekisteri/repositories/HenkiloRepository.java, oppijanumerorekisteri-domain/src/main/java/fi/vm/sade/oppijanumerorekisteri/repositories/impl/HenkiloRepositoryImpl.java, oppijanumerorekisteri-domain/src/test/java/fi/vm/sade/oppijanumerorekisteri/repositories/HenkiloRepositoryTests.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/controllers/Service2ServiceController.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/HenkiloService.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/HenkiloServiceImpl.java, oppijanumerorekisteri-service/src/main/resources/db/migration/V20211115120000000__municipality_and_birthdate_indexes.sql, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/controllers/Service2ServiceControllerTest.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/services/HenkiloServiceTest.java
=> KJHH-2064: Add endpoint for fetching persons by municipality and dob

oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/controllers/YleistunnisteController.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/OppijaTuontiServiceImpl.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/PermissionCheckerImpl.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/controllers/YleistunnisteControllerTest.java
* Hetu as mandatory field
* Minimal set of attributes
* kansallisuus hard-coded to "unknown"
=> KJHH-2100: Define custom DTO for Yleistunniste creation

oppijanumerorekisteri-domain/pom.xml, oppijanumerorekisteri-domain/src/main/java/fi/vm/sade/oppijanumerorekisteri/aspects/LogExecutionTimeAspect.java, oppijanumerorekisteri-domain/src/main/java/fi/vm/sade/oppijanumerorekisteri/logging/LogExecutionTime.java, oppijanumerorekisteri-domain/src/main/java/fi/vm/sade/oppijanumerorekisteri/repositories/impl/HenkiloRepositoryImpl.java, oppijanumerorekisteri-domain/src/test/java/fi/vm/sade/oppijanumerorekisteri/aspects/LogExecutionTimeAspectTest.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/clients/impl/AtaruClientImpl.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/clients/impl/HakuappClientImpl.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/controllers/HenkiloController.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/DuplicateServiceImpl.java, oppijanumerorekisteri-service/src/main/resources/application.yml
* Attempt to pinpoint duplicate search hotspots
=> Add aspect for logging method execution times

oppijanumerorekisteri-domain/src/main/java/fi/vm/sade/oppijanumerorekisteri/repositories/impl/HenkiloRepositoryImpl.java, oppijanumerorekisteri-domain/src/test/java/fi/vm/sade/oppijanumerorekisteri/repositories/impl/HenkiloRepositoryImplTest.java
* Ensure that date format used in similarity comparison conforms to
one defined in database date_to_char function
=> KJHH-2112: Fix date format used in duplicate search

oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/clients/impl/AtaruClientImpl.java
* fetch applications in parallel
=> Adjust ataru integration to speed up duplicate search

oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/clients/impl/AtaruClientImpl.java, oppijanumerorekisteri-service/src/test/resources/clients/ataru/output.json
=> KJHH-2158: Mark ataru as origin for application data from ataru

oppijanumerorekisteri-service/pom.xml, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/YksilointiServiceImpl.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/services/impl/YksilointiServiceImplTest.java
* Log compared names to ease up possible problem resolving
=> KJHH-2191: Add logging to VTJ name comparison

oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/YksilointiServiceImpl.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/services/impl/YksilointiServiceImplTest.java
* Do not use nickname in VTJ comparison if it is not defined
=> KJHH-2192: Existence check: Remove nickname in VTJ comparison

oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/configurations/SwaggerConfiguration.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/controllers/CasController.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/controllers/HenkiloController.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/controllers/KoodistoController.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/controllers/OppijaController.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/controllers/Service2ServiceController.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/controllers/StaticController.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/controllers/YleistunnisteController.java
* Add lock symbol for endpoints requiring authorization
* Hide deprecated endpoints
* Hide controllers meant for internal use
=> KJHH-2201: Clean up swagger documentation

oppijanumerorekisteri-domain/src/main/java/fi/vm/sade/oppijanumerorekisteri/models/Henkilo.java, oppijanumerorekisteri-domain/src/test/java/fi/vm/sade/oppijanumerorekisteri/repositories/TurvaKieltoTest.java, oppijanumerorekisteri-domain/src/test/resources/turvakielto/test_data_turvakielto.sql, oppijanumerorekisteri-domain/src/test/resources/turvakielto/truncate_data.sql, oppijanumerorekisteri-service/src/main/resources/db/migration/V20221129000000000__turvakielto_siivous.sql, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/IntegrationTest.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/TestApplication.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/controllers/OppijaControllerIntegrationTest.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/migrations/TurvaKieltoMigrationTest.java, oppijanumerorekisteri-service/src/test/resources/migration/test_data_turvakielto_migration.sql
- Refactor tests to remove @SpringBootApplication annotation from test class
- KJHH-2231 remove information when persisting person if turvaKielto
=> KJHH-2231 remove information when persisting person if turvaKielto

oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/controllers/YleistunnisteController.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/controllers/YleistunnisteControllerTest.java
* Do not accept empty string as SSN
=> KJHH-2240: Adjust mass creation validation routines

oppijanumerorekisteri-api/src/main/java/fi/vm/sade/oppijanumerorekisteri/dto/TuontiKoosteRequest.java, oppijanumerorekisteri-domain/src/main/java/fi/vm/sade/oppijanumerorekisteri/repositories/TuontiRepository.java, oppijanumerorekisteri-service/src/main/resources/db/migration/V20221215120000000__tuontikooste_fix.sql, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/controllers/OppijaControllerIntegrationTest.java, oppijanumerorekisteri-service/src/test/resources/controller/oppija/integration/fixture/tuonti-test-fixture.sql, oppijanumerorekisteri-service/src/test/resources/controller/oppija/integration/response/kooste-superuser.json, oppijanumerorekisteri-service/src/test/resources/controller/oppija/integration/response/kooste-tuonti1.json
* Adjust tuontikooste view not to expect existence of tuonti_rivi
* Add new attribute to see whether the batch has been handled
=> KJHH-2242: Tuontikooste: Better handling of errored batches

oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/OppijaTuontiService.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/OppijaTuontiAsyncServiceImpl.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/services/impl/OppijaTuontiServiceImpl.java, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/services/impl/OppijaTuontiAsyncServiceImplTest.java
* Retry batch execution on known recoverable exception types
* Use smaller batch size by default
=> KJHH-2247: OppijaTuontiAsyncServiceImpl: Improve error handling

oppijanumerorekisteri-api/src/main/java/fi/vm/sade/oppijanumerorekisteri/dto/OppijaCreateDto.java, oppijanumerorekisteri-api/src/main/java/fi/vm/sade/oppijanumerorekisteri/dto/OppijaTuontiCreateDto.java, oppijanumerorekisteri-api/src/main/java/fi/vm/sade/oppijanumerorekisteri/dto/OppijaTuontiRiviCreateDto.java, oppijanumerorekisteri-service/src/main/java/fi/vm/sade/oppijanumerorekisteri/controllers/YleistunnisteController.java
* Clearly indicate mandatory fields for mass import input(s)
=> KJHH-2276: Improve swagger documentation

oppijanumerorekisteri-service/src/main/resources/db/migration/V20230303120000000__duplicate_search_bugfix.sql
* prefix with public schema to better cope with db dumps
=> KJHH-2298: Adjust db function definition

oppijanumerorekisteri-api/src/main/java/fi/vm/sade/oppijanumerorekisteri/dto/KansalaisuusDto.java, oppijanumerorekisteri-api/src/main/java/fi/vm/sade/oppijanumerorekisteri/dto/KielisyysDto.java, oppijanumerorekisteri-api/src/main/java/fi/vm/sade/oppijanumerorekisteri/dto/OppijaCreateDto.java, oppijanumerorekisteri-api/src/test/java/fi/vm/sade/oppijanumerorekisteri/dto/OppijaCreateDtoTest.java
=> KJHH-2287: POST /oppija - adjust validation routines

oppijanumerorekisteri-api/pom.xml, oppijanumerorekisteri-api/src/main/java/fi/vm/sade/oppijanumerorekisteri/dto/YhteystietoDto.java, oppijanumerorekisteri-api/src/main/java/fi/vm/sade/oppijanumerorekisteri/dto/YhteystietoTyyppi.java, oppijanumerorekisteri-api/src/test/java/fi/vm/sade/oppijanumerorekisteri/dto/YhteystietoDtoTest.java, oppijanumerorekisteri-service/src/main/resources/db/migration/V20230425120000000__trim_contact_information_fields.sql, oppijanumerorekisteri-service/src/test/java/fi/vm/sade/oppijanumerorekisteri/controllers/HenkiloControllerTest.java
* email
* zip code
* phone number(s)
=> KJHH-2143: Add some validations to contact information fields

.github/workflows/build.yml, oppijanumerorekisteri-service/src/main/resources/db/migration/V20240605000000000__add_henkiloviite_oid_indexes.sql
Change deploy-container to use the new pipeline
=> arm64 build
